# Site settings
title: KeyboardGorillas
header-img: img/home-bg.jpg
email: keyboardgorillas@gmail.com
copyright_name: KeyboardGorillas
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://keyboardgorillas.github.io"
twitter_username: keyboardgorillas
github_username:  keyboardgorillas
facebook_username:  KeyboardGorillas
email_username:  keyboardgorillas@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
